// <auto-generated />
// Built-in fallback generated from the Ikuya Mitty DMU mitigation sheet tabs on 2026-07-18.
using System.Collections.Generic;

namespace DMUMits;

public static partial class DmuMitigationData
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<PartySlot, string>> FallbackSheetMitigationOverrides =
        new Dictionary<string, IReadOnlyDictionary<PartySlot, string>>
        {
            // These baked rows moved to better ACT events in the current sheet merge.
            ["P2_WINGS_OF_DESTRUCTION_01"] = M(),
            ["P3_STOMP_A_MOLE_01"] = M(),
            ["P5_STRAY_ENTROPY_01"] = M(),
            ["P1_MYSTERY_MAGIC_01"] = M(mt: "Party Mit (GNB/DRK)", ot: "Reprisal + Party Mit (1)", whm: "Temperance", ast: "Neutral Sect + Sun Sign", sch: "Spreadlo + Sacred Soil (2)", sge: "Kerachole (2) + Zoe Shields", d1: "Feint", d3: "Party Mit (1)"),
            ["P1_WAVE_CANNON_01"] = M(mt: "Party Mit (WAR/PLD) / -> Party Mit (GNB/DRK)", whm: "Divine Caress / -> Temperance", ast: "-> Neutral Sect + Sun Sign", sch: "Seraph / -> Sacred Soil", sge: "Holos / -> Kerachole", d1: "-> Feint"),
            ["P1_DOUBLE_TROUBLE_TRAP_01"] = M(mt: "-> Party Mit (GNB/DRK)", whm: "-> Temperance", ast: "-> Neutral Sect + Sun Sign", sch: "Seraph", sge: "-> Holos", d1: "-> Feint", d4: "Addle"),
            ["P1_LIGHT_OF_JUDGMENT_01"] = M(mt: "Reprisal", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Sacred Soil", sge: "Kerachole", d2: "Feint", d4: "-> Addle"),
            ["P1_GRAVITAS_II_01"] = M(ast: "Macrocosmos", sch: "Seraphism (4)"),
            ["P1_GRAVITAS_II_02"] = M(whm: "Liturgy of the Bell (3)", sch: "Expedient + Fey Illumination", sge: "Kerachole + Philosophia"),
            ["P1_DOUBLE_TROUBLE_TRAP_02"] = M(ot: "Reprisal + Party Mit", sch: "Spreadlo + Sacred Soil / -> Expedient + Fey Illumination", sge: "Panhaima + Zoe Shields", d3: "Party Mit"),
            ["P1_LIGHT_OF_JUDGMENT_02"] = M(mt: "Reprisal + Party Mit", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "-> Sacred Soil", sge: "Kerachole / -> Panhaima", d1: "Feint"),
            ["P1_DOUBLE_TROUBLE_TRAP_03"] = M(whm: "Temperance", ast: "Neutral Sect"),
            ["P1_INDULGENT_WILL_01"] = M(whm: "Divine Caress / -> Temperance", ast: "Sun Sign", sch: "Sacred Soil", sge: "Kerachole"),
            ["P1_MYSTERY_MAGIC_02_ACT_02"] = M(ot: "Reprisal", whm: "-> Temperance", ast: "-> Sun Sign", sch: "-> Sacred Soil", sge: "-> Kerachole"),
            ["P2_ULTIMATE_EMBRANCE_01"] = M(whm: "Assist Tanks (1)", sch: "Spreadlo (2)", sge: "Holos (3)", d2: "Feint"),
            ["P2_FORSAKEN_01"] = M(mt: "Reprisal", ot: "Party Mit", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Sacred Soil / -> Spreadlo", sge: "Kerachole + Zoe Shields / -> Holos", d1: "Feint", d3: "Party Mit", d4: "Addle"),
            ["P2_TOWERS_I_01"] = M(sch: "Seraph + Fey Illumination / -> Sacred Soil", sge: "Panhaima / -> Kerachole"),
            ["P2_TOWERS_II_01"] = M(sch: "Seraph / -> Fey Illumination", sge: "-> Panhaima"),
            ["P2_TOWERS_III_01"] = M(mt: "Party Mit", ot: "Reprisal", ast: "Macrocosmos", sch: "Sacred Soil", sge: "Kerachole"),
            ["P2_TOWERS_IV_01"] = M(mt: "-> Party Mit (GNB/DRK)", sch: "-> Sacred Soil", sge: "-> Kerachole"),
            ["P2_TOWERS_V_01"] = M(whm: "Liturgy of the Bell", sch: "Expedient"),
            ["P2_TOWERS_VI_01"] = M(mt: "Reprisal", whm: "Plenary Indulgence + Temperance", ast: "Collective Unconscious + Neutral Sect", sch: "Seraphism / -> Expedient", sge: "Philosophia"),
            ["P2_TOWERS_VII_01"] = M(whm: "Divine Caress / -> Temperance", ast: "Sun Sign", sch: "Sacred Soil", sge: "Kerachole"),
            ["P2_TOWERS_VIII_01"] = M(whm: "-> Temperance", ast: "-> Sun Sign", sch: "-> Sacred Soil", sge: "-> Kerachole"),
            ["P2_LIGHT_OF_JUDGEMENT_01"] = M(ot: "Reprisal + Party Mit", sch: "Spreadlo + Sacred Soil", sge: "Kerachole + Holos (3) + Zoe Shields", d1: "Feint", d3: "Party Mit", d4: "Addle"),
            ["P2_WINGS_OF_DESTRUCTION_02"] = M(mt: "Reprisal + Party Mit (4)", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Sacred Soil + Fey Illumination + Seraph", sge: "Kerachole + Panhaima", d2: "Feint"),
            ["P2_ULTIMATE_EMBRACE_01"] = M(mt: "-> Reprisal + Party Mit", whm: "-> Plenary Indulgence", ast: "-> Collective Unconscious", sch: "-> Sacred Soil + Fey Illumination + Seraph", sge: "-> Kerachole + Panhaima", d2: "-> Feint"),
            ["P3_BOWELS_OF_AGONY_01"] = M(mt: "Reprisal (5)", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Sacred Soil (1)", sge: "Kerachole (1)", d1: "Feint (Chaos)"),
            ["P3_STRAY_FLAMES_TSUNAMI_01"] = M(mt: "Party Mit", ot: "Reprisal", sch: "Spreadlo (9) + Sacred Soil", sge: "Zoe Shields + Kerachole"),
            ["P3_THUNDER_III_01"] = M(ot: "-> Reprisal", sch: "Expedient (2)", sge: "Holos (2)", d4: "Addle (Exdeath)"),
            ["P3_STRAY_FLAMES_TSUNAMI_02"] = M(ot: "Party Mit", whm: "Temperance", ast: "Neutral Sect", sch: "Seraph / -> Expedient", sge: "-> Holos"),
            ["P3_ULTIMA_BLASTER_01"] = M(mt: "Reprisal", whm: "-> Temperance", ast: "Sun Sign / -> Neutral Sect", sch: "Sacred Soil + Fey Illumination + Seraphism", sge: "Kerachole + Panhaima", d2: "Feint (Chaos)", d3: "Party Mit"),
            ["P3_VACUUM_WAVE_01"] = M(mt: "LB3 (6) / -> Reprisal", ot: "LB3 (6)", whm: "Plenary Indulgence / -> Temperance", ast: "Collective Unconscious / -> Neutral Sect + Sun Sign", sch: "-> Sacred Soil + Fey Illumination", sge: "-> Kerachole + Panhaima", d2: "-> Feint", d3: "-> Party Mit"),
            ["P3_CYCLONE_01"] = M(mt: "-> Reprisal", whm: "Divine Caress / -> Plenary Indulgence", ast: "-> Collective Unconscious / + Sun Sign", sch: "-> Sacred Soil + Fey Illumination", sge: "-> Kerachole + Panhaima", d2: "-> Feint", d3: "-> Party Mit"),
            ["P3_THE_DECISIVE_BATTLE_01"] = M(ot: "Reprisal (Exdeath)", sch: "Spreadlo (8)", sge: "Zoe Shields"),
            ["P3_EARTHQUAKE_01"] = M(mt: "Party Mit (GNB/DRK)", ast: "Macrocosmos", sch: "Sacred Soil", sge: "Kerachole + Philosophia", d1: "Feint (Chaos)"),
            ["P3_SHOCKING_IMPACT_SHOCKWAVE_01"] = M(mt: "Reprisal + Party Mit (WAR/PLD) / -> Party Mit (GNB/DRK)", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "-> Sacred Soil", sge: "-> Kerachole"),
            ["P3_SHOCKING_IMPACT_SHOCKWAVE_02"] = M(ot: "Party Mit (GNB/DRK)", whm: "Liturgy of the Bell", sch: "Expedient + Seraph + Sacred Soil", sge: "Holos + Kerachole"),
            ["P3_BLACK_HOLES_II_01"] = M(ot: "Party Mit (WAR/PLD) / -> Party Mit (GNB/DRK)", whm: "Temperance + Divine Caress", ast: "Neutral Sect + Sun Sign", sch: "Seraph / -> Expedient + Sacred Soil", sge: "-> Holos + Kerachole"),
            ["P3_BLACK_HOLES_II_02"] = M(ot: "-> Party Mit (GNB/DRK)", whm: "-> Temperance", ast: "-> Neutral Sect + Sun Sign", sch: "-> Expedient + Sacred Soil", sge: "-> Holos"),
            ["P3_BLACK_HOLES_II_03"] = M(whm: "-> Temperance", ast: "-> Neutral Sect + Sun Sign", sch: "Fey Illumination / -> Expedient", sge: "-> Holos"),
            ["P3_THUNDER_III_02"] = M(mt: "Reprisal", whm: "-> Temperance", ast: "-> Neutral Sect", sch: "Spreadlo + Sacred Soil / -> Fey Illumination", sge: "Zoe Shields + Kerachole", d2: "Feint (Chaos)", d4: "Addle (Exdeath)"),
            ["P3_BLACK_HOLES_III_01"] = M(sge: "Panhaima / -> Panhaima (7-8th Set)", d3: "Party Mit / -> Party Mit (7-8th Set)"),
            ["P3_SHOCKING_IMPACT_SHOCKWAVE_03"] = M(whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Sacred Soil", sge: "Kerachole"),
            ["P3_STOMP_A_MOLE_CASTBAR_01"] = M(mt: "Reprisal (3) + Party Mit", ot: "Reprisal (3)", sch: "Seraphism (7) + Sacred Soil", sge: "Kerachole", d1: "Feint (Chaos)"),
            ["P4_GRAND_CROSS_01"] = M(whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Spreadlo + Sacred Soil", sge: "Kerachole + Philosophia + Holos", d2: "Feint (1)"),
            ["P4_INFERNO_TSUNAMI_01"] = M(whm: "-> Plenary Indulgence", ast: "-> Collective Unconscious", sch: "-> Sacred Soil", sge: "-> Holos", d3: "Party Mit"),
            ["P4_GRAND_CROSS_02"] = M(whm: "Temperance", ast: "Neutral Sect", sch: "Expedient + Fey Illumination / -> Sacred Soil", sge: "Panhaima / -> Holos", d3: "-> Party Mit"),
            ["P4_INFERNO_TSUNAMI_02"] = M(ot: "Party Mit (GNB/DRK)", whm: "-> Temperance", ast: "Sun Sign / -> Neutral Sect", sch: "Seraph / -> Expedient + Fey Illumination", sge: "-> Panhaima"),
            ["P4_GRAND_CROSS_03"] = M(ot: "Party Mit (WAR/PLD) / -> Party Mit (GNB/DRK)", whm: "Divine Caress / -> Temperance", ast: "-> Neutral Sect + Sun Sign", sch: "Seraph / -> Expedient + Fey Illumination", sge: "Zoe Shields"),
            ["P4_FLOOD_OF_NAUGHT_01"] = M(whm: "Liturgy of the Bell", ast: "Macrocosmos", sch: "Sacred Soil", sge: "Kerachole"),
            ["P4_DEATH_BOLT_WAVE_01"] = M(mt: "Party Mit", sch: "-> Sacred Soil", sge: "-> Kerachole"),
            ["P4_ULTIMA_UPSURGE_01"] = M(mt: "Reprisal", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Sacred Soil", sge: "Kerachole", d1: "Feint", d4: "Addle"),
            ["P4_DEATH_BOLT_WAVE_02"] = M(whm: "-> Plenary Indulgence", ast: "-> Collective Unconscious", sch: "-> Sacred Soil", sge: "-> Kerachole"),
            ["P4_ULTIMA_UPSURGE_02"] = M(ot: "Reprisal", sch: "Sacred Soil", sge: "Kerachole"),
            ["P5_ULTIMA_REPEATER_01"] = M(mt: "Reprisal", ot: "Party Mit (1)", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Spreadlo + Sacred Soil", sge: "Zoe Shields + Holos + Kerachole", d3: "Party Mit (1)"),
            ["P5_FELL_FORCES_01"] = M(mt: "-> Reprisal", whm: "-> Plenary Indulgence", ast: "-> Collective Unconscious", sch: "-> Sacred Soil", sge: "-> Holos + Kerachole"),
            ["P5_CHAOTIC_FLOOD_01"] = M(whm: "Temperance", ast: "Neutral Sect", sch: "Expedient", sge: "Panhaima / -> Holos"),
            ["P5_MADDENING_ORCHESTRA_01"] = M(ot: "Reprisal", whm: "Divine Caress / -> Temperance", ast: "Sun Sign", sch: "Sacred Soil + Fey Illumination / -> Expedient", sge: "Kerachole", d2: "Feint"),
            ["P5_FELL_FORCES_02"] = M(ot: "-> Reprisal", ast: "-> Sun Sign", sch: "-> Sacred Soil + Fey Illumination", sge: "-> Kerachole", d2: "-> Feint"),
            ["P5_CELESTRIAD_01"] = M(mt: "Party Mit", sch: "Seraph (4)"),
            ["P5_ULTIMA_REPEATER_02"] = M(mt: "Reprisal", ot: "Party Mit (1)", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Sacred Soil", sge: "Kerachole", d1: "Feint (5)", d3: "Party Mit (1)", d4: "Addle (5)"),
            ["P5_FELL_FORCES_03_ACT_02"] = M(mt: "-> Reprisal", ot: "-> Party Mit", whm: "-> Plenary Indulgence", ast: "-> Collective Unconscious", sch: "-> Sacred Soil", sge: "-> Kerachole", d1: "-> Feint", d3: "-> Party Mit", d4: "-> Addle"),
            ["P5_STRAY_ENTROPY_02"] = M(ot: "Reprisal (3)"),
            ["P5_MADDENING_ORCHESTRA_02"] = M(whm: "Assist Tanks (2)", sch: "Sacred Soil (2)", sge: "Kerachole (2)"),
            ["P5_FELL_FORCES_04"] = M(whm: "Assist Tanks (2)"),
            ["P5_FORSAKEN_01"] = M(mt: "Reprisal + Party Mit", whm: "Temperance", ast: "Neutral Sect + Collective Unconscious", sch: "Spreadlo + Fey Illumination + Sacred Soil", sge: "Zoe Shields + Holos + Kerachole", d2: "Feint"),
            ["P5_FORSAKEN_BONDS_01"] = M(mt: "-> Reprisal + Party Mit (GNB/DRK)", whm: "Liturgy of the Bell / -> Temperance", ast: "-> Neutral Sect + Collective Unconscious", sch: "Seraphism / -> Fey Illumination + Sacred Soil", sge: "Philosophia / -> Holos + Kerachole", d2: "-> Feint"),
            ["P5_FORSAKEN_02"] = M(mt: "-> Reprisal + Party Mit (GNB/DRK)", whm: "-> Temperance", ast: "Macrocosmos / -> Neutral Sect + Collective Unconscious", sch: "Expedient / -> Fey Illumination + Sacred Soil", sge: "Panhaima / -> Holos + Kerachole", d2: "-> Feint"),
            ["P5_FORSAKEN_BONDS_02"] = M(mt: "-> Reprisal + Party Mit (GNB/DRK)", whm: "-> Temperance", ast: "-> Neutral Sect", sch: "-> Fey Illumination + Expedient", sge: "-> Holos + Panhaima", d2: "-> Feint"),
            ["P5_FORSAKEN_03"] = M(ot: "Reprisal + Party Mit", whm: "Divine Caress + Plenary Indulgence / -> Temperance", ast: "Sun Sign", sch: "-> Expedient", sge: "-> Holos + Panhaima", d1: "Feint", d3: "Party Mit", d4: "Addle"),
            ["P5_FORSAKEN_BONDS_03"] = M(ot: "-> Reprisal + Party Mit (GNB/DRK)", whm: "-> Plenary Indulgence", ast: "-> Sun Sign", sch: "-> Expedient", sge: "-> Panhaima", d1: "-> Feint", d3: "-> Party Mit", d4: "-> Addle"),
            ["P5_FORSAKEN_04"] = M(ot: "-> Reprisal + Party Mit (GNB/DRK)", whm: "-> Plenary Indulgence", ast: "-> Sun Sign", sch: "Seraph", sge: "-> Panhaima", d1: "-> Feint", d3: "-> Party Mit", d4: "-> Addle"),
            ["P5_FORSAKEN_BONDS_04"] = M(ot: "-> Reprisal + Party Mit (GNB/DRK)", ast: "-> Sun Sign", sch: "Seraph + Sacred Soil", sge: "Kerachole", d1: "-> Feint", d3: "-> Party Mit", d4: "-> Addle"),
            ["P5_FORSAKEN_NULL_01"] = M(mt: "Enrage!"),
        };

    private static bool TryGetFallbackSheetMitigationOverride(string eventId, out IReadOnlyDictionary<PartySlot, string> mitigations)
    {
        return FallbackSheetMitigationOverrides.TryGetValue(eventId, out mitigations!);
    }
}
