// <auto-generated />
// Built-in LPDU sheet generated from https://docs.google.com/spreadsheets/d/1aA_qF_UsoS51MCDZ4PwQHhprpK7eGO8TXOdZ7pQlkV0 on 2026-07-22.
// LPDU Fake Melee Extras are not mapped because DMU Mits has no fake-melee-specific party slot yet.
using System.Collections.Generic;

namespace DMUMits;

public static partial class DmuMitigationData
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<PartySlot, string>> LpduSheetMitigationOverrides =
        new Dictionary<string, IReadOnlyDictionary<PartySlot, string>>
        {
            ["P1_REVOLTING_RUIN_III_1_01"] = M(mt: "Kitchen sink", ot: "Short cotank + Provoke", whm: "Benison + Aquaveil MT", ast: "All single target mit MT -> Ewer OT", sch: "Protraction + Spreadlo off mt after 2nd hit + Excog OT", sge: "Haima + Taurochole MT / Eprog between hits then prep Zoe"),
            ["P1_MYSTERY_MAGIC_01"] = M(mt: "party mit after buster, Reprisal after knock", ot: "party mit after knock, shake/veil after stack/spread", whm: "Temperance", ast: "Neutral Sect + Sun Sign", sch: "Expedient", sge: "Panhaima + Physis II", d1: "Feint", d3: "90s", d4: "Addle"),
            ["P1_WAVE_CANNON_01"] = M(whm: "Divine Caress", ast: "Collective Unconscious", sch: "Succor", sge: "Zoe Eprog"),
            ["P1_DOUBLE_TROUBLE_TRAP_01"] = M(whm: "Plenary Indulgence", sch: "Succor + Sacred Soil + Illum", sge: "Eprog + Kerachole"),
            ["P1_LIGHT_OF_JUDGMENT_01"] = M(ot: "Reprisal", whm: "Asylum", sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole", d2: "Feint"),
            ["P1_HYPERDRIVE_1_01"] = M(mt: "Short cotank", ot: "Kitchen Sink", whm: "Benison OT", ast: "Card mits + Celestial Intersection OT", sch: "Tether", sge: "Taurochole OT"),
            ["P1_GRAVITAS_II_01"] = M(whm: "Liturgy of the Bell", ast: "Macrocosmos", sch: "Seraphism+ Sacred Soil + Succor", sge: "Philosophia + Eprog + Kerachole"),
            ["P1_REVOLTING_RUIN_III_1_02"] = M(mt: "Provoke", ot: "Invuln", whm: "Bene if drk"),
            ["P1_GRAVITAS_II_02"] = M(mt: "Reprisal @ 14 sec debuff", sch: "Seraphism + Succor + Seraph", sge: "Philosophia + Eprog + Holos"),
            ["P1_DOUBLE_TROUBLE_TRAP_02"] = M(mt: "Party mit @ 1 sec debuff, Shake/veil after knock", ot: "Reprisal on knockback", whm: "Plenary Indulgence before knock", ast: "Collective Unconscious", sch: "Succor + Sacred Soil + Seraph after knock", sge: "Physis II + Eprog + Holos + Kerachole", d1: "Feint", d3: "90s", d4: "Addle"),
            ["P1_LIGHT_OF_JUDGMENT_02"] = M(ot: "Party mit", whm: "Asylum off cd", sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole"),
            ["P1_HYPERDRIVE_2_01"] = M(mt: "Invuln (ks if war)", ast: "Neutral Sect off cd"),
            ["P1_DOUBLE_TROUBLE_TRAP_03"] = M(whm: "Temperance off cd", ast: "Sun Sign", sch: "Succor + Expedient", sge: "Eprog + Panhaima + Physis II", d2: "Feint"),
            ["P1_INDULGENT_WILL_01"] = M(mt: "Reprisal on confusion", whm: "Divine Caress", sch: "Succor", sge: "Eprog"),
            ["P1_MYSTERY_MAGIC_02_ACT_02"] = M(sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole"),
            ["P2_ULTIMATE_EMBRANCE_01"] = M(mt: "Kitchen Sink (invuln solo if war)", ot: "Kitchen Sink + Reprisal", whm: "Aqua veil MT + Benison both", ast: "All single target mit MT / Exalt OT + Celestial Intersection both", sch: "Spreadlo off MT + Sacred Soil 80% Cast", sge: "Haima MT + Taurochole OT / Eprog both"),
            ["P2_FORSAKEN_01"] = M(mt: "Party Mit + Reprisal", ot: "Party mit", whm: "Plenary Indulgence // Asylum off cd", ast: "Collective Unconscious", sch: "Spreadlo + Sacred Soil", sge: "Zoe Eprog + Kerachole + Holos + Physis II", d1: "Feint", d3: "90s", d4: "Addle"),
            ["P2_TOWERS_I_01"] = M(sch: "Succor", sge: "Eprog + Holos"),
            ["P2_TOWERS_II_01"] = M(whm: "Liturgy of the Bell off cd", ast: "Macrocosmos", sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole + Philosophia"),
            ["P2_TOWERS_III_01"] = M(ast: "Neutral Sect + Sun Sign", sch: "Succor + Sacred Soil + Expedient", sge: "Eprog + Kerachole + Philosophia", d2: "Feint"),
            ["P2_TOWERS_IV_01"] = M(ot: "Reprisal", whm: "Temperance", sch: "Succor + Expedient", sge: "Eprog + Philosophia"),
            ["P2_TOWERS_V_01"] = M(whm: "Divine Caress", ast: "Collective Unconscious", sch: "Succor // Seraph + Illum off cd", sge: "Eprog + Panhaima"),
            ["P2_TOWERS_VI_01"] = M(mt: "Reprisal", whm: "Plenary Indulgence", sch: "Succor // Seraph + Illum off cd", sge: "Eprog + Panhaima"),
            ["P2_TOWERS_VII_01"] = M(sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole"),
            ["P2_TOWERS_VIII_01"] = M(sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole"),
            ["P2_LIGHT_OF_JUDGEMENT_01"] = M(mt: "Party Mit", ot: "Party Mit + Reprisal", whm: "Asylum off cd", sch: "Spreadlo + Sacred Soil", sge: "Zoe Eprog + Kerachole", d1: "Feint", d3: "90s", d4: "Addle"),
            ["P2_WINGS_OF_DESTRUCTION_02"] = M(mt: "Kitchen (no short) + Reprisal", ot: "Kitchen (no short)", sch: "Excog mt", sge: "Haima + Taurochole MT", d2: "Feint"),
            ["P2_ULTIMATE_EMBRACE_01"] = M(mt: "Short", ot: "Short", whm: "Aqua veil MT + Benison both", ast: "All single target mit MT / Exalt OT + Celestial Intersection both", sch: "Adlo both + Sacred Soil", sge: "Ediag Both + Kerachole"),
            ["P3_BOWELS_OF_AGONY_01"] = M(mt: "Reprisal", whm: "Regen both tanks + Asylum", sge: "Ediag both tanks // Eprog + Kerachole + Physis II", d1: "Feint chaos autos"),
            ["P3_STRAY_FLAMES_TSUNAMI_01"] = M(ot: "Party Mit", whm: "Plenary Indulgence", sch: "Spreadlo", sge: "Philosophia + Physis II + Eprog + Holos + Prep Zoe", d2: "Feint chaos autos"),
            ["P3_THUNDER_III_01"] = M(mt: "Shorts + Ramp+ 90s (First hit)", ot: "Reprisal + Shorts + Ramp + 90s (Second hit)", whm: "Aqua veil MT + Benison both", ast: "All single target mit MT / Exalt OT + Celestial Intersection both", sch: "Sacred Soil buster free here!!! + Expedient", sge: "Pepsis + Zoe Eprog + Kerachole after 2nd buster", d4: "Addle"),
            ["P3_STRAY_FLAMES_TSUNAMI_02"] = M(mt: "Reprisal during lat/long cast (make sure it hits chaos)", whm: "Temperance + Divine Caress", ast: "Neutral Sect + Sun Sign", sch: "Succor + Expedient", sge: "Zoe Eprog + Kerachole"),
            ["P3_ULTIMA_BLASTER_PREP_01"] = M(whm: "Liturgy of the Bell", sch: "Succor+ Sacred Soil + Seraphism", sge: "Pneuma + Physis II + Panhaima + Eprog"),
            ["P3_VACUUM_WAVE_01"] = M(whm: "Asylum", ast: "Collective Unconscious", sch: "Succor+ Sacred Soil + Seraphism", sge: "Eprog + Kerachole", d3: "90s"),
            ["P3_CYCLONE_01"] = M(mt: "Party Mit + Shorts", ot: "Shorts", sch: "Succor + Seraphism + Seraph", sge: "Eprog + Kerachole"),
            ["P3_THUNDER_III_2_01"] = M(mt: "Invuln"),
            ["P3_THE_DECISIVE_BATTLE_01"] = M(mt: "STAND UNDER + VOKE CHAOS (make sure both bosses cant move before moving under)", ot: "STAND UNDER + VOKE EXDEATH (make sure both bosses cant move before moving under)"),
            ["P3_THUNDER_III_3_01"] = M(mt: "120s (use late) (Second hit) + Shorts (not corundum)", ot: "120s (use late) + Reprisal (First hit) (not corundum)", whm: "Aqua veil MT + Benison both", ast: "All single target mit MT / Exalt OT + Celestial Intersection both", sch: "Spreadlo", sge: "Zoe Eprog + Haima MT + Taurochole OT + Ediag both after hits"),
            ["P3_EARTHQUAKE_01"] = M(mt: "Shorts on 1hp (warrior use equilibrium after hp drops to 1)", ot: "Shorts on 1hp (warrior use equilibrium after hp drops to 1)", whm: "Plenary Indulgence + Benediction Healer Accretion (check pastebin line 107)", ast: "Macrocosmos (Check pastebin)", sge: "Physis II + Krasis + Druo healer // Eprog after first pop // Pepsis + Prognosis + Ixo after vuln for safety", d1: "Feint chaos autos"),
            ["P3_SHOCKING_IMPACT_SHOCKWAVE_01"] = M(mt: "Reprisal early", ot: "Party Mit", whm: "Asylum off cd", ast: "Collective Unconscious", sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole"),
            ["P3_THUNDER_III_4_01"] = M(ot: "Invuln"),
            ["P3_SHOCKING_IMPACT_SHOCKWAVE_02"] = M(mt: "Party mit", whm: "Temperance + Divine Caress", ast: "Neutral Sect + Sun Sign", sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole + Holos late"),
            ["P3_BLACK_SPARK_01"] = M(sch: "Succor(s)+ Expedient", sge: "Eprog each set // Physis II + Panhaima as last beam hits", d2: "Feint chaos autos"),
            ["P3_THUNDER_III_02"] = M(mt: "Shorts + Ramp + 90s (Second hit)", ot: "Shorts + Ramp+ 90s (First hit) + Reprisal", whm: "Plenary Indulgence + Aqua veil MT + Benison both", ast: "All single target mit MT / Exalt OT + Celestial Intersection both + Collective Unconscious", sch: "Sacred Soil", sge: "Panhaima + Philosophia + Physis II + Eprog", d4: "Addle"),
            ["P3_BLACK_HOLES_III_01"] = M(mt: "Shorts on cd from this point", ot: "Shorts on cd from this point"),
            ["P3_SHOCKING_IMPACT_SHOCKWAVE_03"] = M(mt: "Face boss NW kefka relative right after 3rd beam", ot: "Party Mit", whm: "Asylum off cd", sch: "Succor + Sacred Soil", sge: "Pneuma white hole + Eprog + Kerachole", d1: "Feint chaos autos", d3: "90s"),
            ["P3_BLACK_SPARK_02"] = M(mt: "120s after last beam", ot: "120s after last beam", whm: "Babysit beam tank", sge: "Haima beam tank, if not haima chaos tank"),
            ["P3_STOMP_A_MOLE_CASTBAR_01"] = M(mt: "Reprisal + Party mit", ot: "Reprisal", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Succor + Seraphism + Sacred Soil", sge: "Eprog + Kerachole + Physis II // Reshield as necessary between hits", d2: "Feint"),
            ["P4_GRAND_CROSS_01"] = M(mt: "90s + Shorts for autos", ot: "90s incase you forgot your stance lol", whm: "Benison + Aquaveil MT // Asylum off cd // Temperance 80% Grand Cross Castbar", ast: "Neutral Sect", sch: "Spreadlo + Sacred Soil", sge: "Kerachole end of Kefka says castbar // Eprog // Holos 80% Grand Cross Castbar"),
            ["P4_INFERNO_TSUNAMI_01"] = M(whm: "Temperance + Divine Caress", ast: "Sun Sign", sch: "Succor + Sacred Soil", sge: "Eprog + Holos"),
            ["P4_GRAND_CROSS_02"] = M(whm: "Temperance", ast: "Sun Sign", sch: "Succor + Expedient + Sacred Soil + Illum", sge: "Eprog + Holos + Panhaima"),
            ["P4_INFERNO_TSUNAMI_02"] = M(ot: "Party mit (Hol/Missionary)", sch: "Succor + Expedient + Illum", sge: "Eprog + Panhaima + Kerachole", d3: "90s"),
            ["P4_GRAND_CROSS_03"] = M(mt: "Shorts to R1", ot: "Party mit (Shake/Veil) Shorts to R2", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Succor + Expedient + Illum + Seraph", sge: "Eprog + Panhaima + Kerachole"),
            ["P4_FLOOD_OF_NAUGHT_01"] = M(whm: "Liturgy of the Bell / all stacks after hit", ast: "Macrocosmos", sch: "Succor + Sacred Soil + Seraph", sge: "Eprog + Physis II"),
            ["P4_DEATH_BOLT_WAVE_01"] = M(sch: "Succor + Sacred Soil", sge: "Pneuma -> Zoe Eprog (after yellow debuff)"),
            ["P4_ULTIMA_UPSURGE_01"] = M(mt: "Reprisal + Party mit (Hol/Missionary)", sch: "Succor + Sacred Soil", sge: "Philosophia + Eprog + Kerachole", d1: "Feint", d4: "Addle"),
            ["P4_DEATH_BOLT_WAVE_02"] = M(mt: "Party mit (Shake)", sge: "Philosophia + Eprog + Kerachole"),
            ["P4_ULTIMA_UPSURGE_02"] = M(ot: "Reprisal", sch: "Succor + Sacred Soil", sge: "Eprog + Kerachole", d2: "Feint"),
            ["P5_ULTIMA_REPEATER_01"] = M(mt: "Reprisal", ot: "Start with aggro! // Party Mit @ Smile quote (shake/veil can be used earlier)", whm: "Asylum + Temperance + Plenary Indulgence", ast: "Neutral Sect + Collective Unconscious", sch: "Spreadlo + Sacred Soil + Fey Illum", sge: "Eprog + Kerachole + Physis II // Haima MT", d3: "90s @ Smile quote"),
            ["P5_FELL_FORCES_01"] = M(mt: "120s + Shorts", ot: "Ramp + 90s + Shorts", whm: "Benison MT + Aquaveil OT", ast: "Celestial Intersection MT + Exalt OT", sch: "Succor(s) + Exped after 1st hit", sge: "Eprog(s) // Holos after 1st hit"),
            ["P5_CHAOTIC_FLOOD_01"] = M(ot: "Reprisal", whm: "Divine Caress", ast: "Sun Sign", sch: "Succor + Exped", sge: "Eprog + Holos"),
            ["P5_MADDENING_ORCHESTRA_01"] = M(mt: "Ramp + 90s + Shorts // Invuln flare", ot: "120s First 2 hits // Shorts flare", whm: "Benison MT", ast: "Celestial Intersection OT", sch: "Succor + Sacred Soil", sge: "Pneuma -> Zoe Eprog + Panhaima + Kerachole", d1: "Feint"),
            ["P5_FELL_FORCES_02"] = M(mt: "Invuln", sch: "Succor(s) + Seraph on 2nd auto hit", sge: "Eprog(s)"),
            ["P5_CELESTRIAD_01"] = M(mt: "Reprisal", whm: "Plenary Indulgence", ast: "Collective Unconscious", sch: "Succor(s) + Seraph", sge: "Eprog(s) + Physis II on 1st tower spawn"),
            ["P5_ULTIMA_REPEATER_02"] = M(mt: "Party Mit", ot: "Reprisal + Party Mit", sch: "Succor(s) + Sacred Soil", sge: "Eprog(s) + Kerachole", d2: "Feint", d3: "90s", d4: "Addle"),
            ["P5_FELL_FORCES_03_ACT_02"] = M(mt: "Shorts", ot: "Shorts", whm: "Benison MT + Aquaveil OT", ast: "Celestial Intersection MT + Exalt OT", sch: "Succor(s) + Sacred Soil", sge: "Eprog(s) + Kerachole"),
            ["P5_STRAY_ENTROPY_02"] = M(sch: "Succor", sge: "Eprog"),
            ["P5_MADDENING_ORCHESTRA_02"] = M(mt: "Ramp + Shorts // 120s Flare", ot: "Ramp + Shorts // Invuln flare", whm: "Benison MT", sch: "Succor(s) + Early Sacred Soil", sge: "Eprog(s) + Early Kerachole + Haima non-invuln tank"),
            ["P5_FELL_FORCES_04"] = M(mt: "90s on 3rd auto and share with ot ->", ot: "Invuln (90s 3rd auto)", whm: "Benediction invulning War/Drk after 2nd auto NOT NEGOTIABLE JUST DO IT", sch: "Succor(s)", sge: "Eprog(s) // KRASIS + TAUROCHOLE INVULN TANK AFTER 2ND AUTO"),
            ["P5_FORSAKEN_01"] = M(mt: "Reprisal", whm: "Asylum + Plenary Indulgence + Liturgy of the Bell", ast: "Neutral Sect + Collective Unconscious", sch: "Fey Illum + Spreadlo // Expedient + Sacred Soil both @ 80% castbar", sge: "Zoe Eprog + Holos // Kerachole both @ 80% castbar", d1: "Feint"),
            ["P5_FORSAKEN_BONDS_01"] = M(sch: "Fey Illum + Succor + Expedient + Sacred Soil", sge: "Eprog + Holos + Kerachole"),
            ["P5_FORSAKEN_02"] = M(whm: "Temperance", ast: "Sun Sign + Macrocosmos", sch: "Fey Illum + Succor + Expedient + Sacred Soil + Seraphism", sge: "Eprog + Holos + Kerachole + Philosophia"),
            ["P5_FORSAKEN_BONDS_02"] = M(sch: "Succor + Expedient + Sacred Soil + Seraphism", sge: "Eprog + Holos + Philosophia + Panhaima"),
            ["P5_FORSAKEN_03"] = M(mt: "Party Mit", ot: "Reprisal + Party Mit", whm: "Divine Caress", sch: "Succor + Expedient + Seraphism", sge: "Eprog + Holos + Philosophia + Panhaima"),
            ["P5_FORSAKEN_BONDS_03"] = M(sch: "Succor + Seraphism + Seraph on cooldown", sge: "Eprog + Philosophia + Panhaima + Physis II", d2: "Feint", d3: "90s", d4: "Addle"),
            ["P5_FORSAKEN_04"] = M(mt: "Shorts to R1", ot: "Shorts to R2", sch: "Succor + Seraph", sge: "Eprog + Panhaima + Physis II // Pneuma after"),
            ["P5_FORSAKEN_BONDS_04"] = M(sch: "Succor + Sacred Soil + Seraph", sge: "Eprog + Kerachole + Physis II"),
            ["P5_FORSAKEN_NULL_01"] = M(mt: "Enrage!"),
        };

    private static int LpduSheetMitigationOverrideCount => LpduSheetMitigationOverrides.Count;

    private static bool TryGetLpduSheetMitigationOverride(string eventId, out IReadOnlyDictionary<PartySlot, string> mitigations)
    {
        return LpduSheetMitigationOverrides.TryGetValue(eventId, out mitigations!);
    }
}
